---
functional:
  - Пользователь должен иметь возможности:
    - Регистрирация на сайте через почту
    - Авторизация по имеющейся учетной записи
    - Восстановление доступа к аккаунту при забытом пароле
    - Авторизация через Discord
    - Авторизация через GitHub
    - Провести пробный баттл без регистрации
    - Создание баттла с ботом, рандомным пользователем, конкретным пользователем
    - Создание турнира с ботом, рандомным пользователем, конкретным пользователем
    - Просмотр профиля с историей баттлов и статистикой
    - Редактирование профиля (смена имени, языка программирования, привязка/отвязка профилей Discord и GitHub)
    - Просмотр лидборда
    - Просмотр истории баттлов за последнее время
    - Создание задач для решения пользователями, а так же просмотр уже созданных задач
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - 
  - 
