---
functional:
  - Пользователь должен иметь возможности:
    - Регистрирация на сайте через почту
    - Авторизация по имеющейся учетной записи
    - Восстановление доступа к аккаунту при забытом пароле
    - Авторизация через Discord
    - Авторизация через GitHub
    - Провести пробный баттл без регистрации
    - Создание баттла с ботом, рандомным пользователем, конкретным пользователем
    - Создание турнира
    - Просмотр профиля с историей баттлов и статистикой
    - Редактирование профиля (смена имени и языка программирования)
    - Просмотр лидборда
    - Просмотр истории баттлов за последнее время
    - Создание задач для решения пользователями, а так же просмотр уже созданных задач
    - Проверка правильности выполнения задачи во время баттла
    - Сдаться во время баттла
    - Отправлять сообщения в чат во время баттла
    - Сбросить написанный код до первоначального состояния во время баттла
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Один игрок не может редактировать код другого во время баттла
  - Один игрок не может копировать код другого во время баттла
